# Set the language.
language: go

# Set test platforms.
os:
  - osx
  - linux

# Set our Go version(s). Mutagen generally only supports a specific version of
# Go at a time, usually the latest, but we also monitor tip to get an idea of
# whether or not the next release is going to break anything.
# NOTE: If you change this version, change the corresponding conditions below in
# code coverage and deployment uploading (see the script and deploy sections).
go:
  - 1.9.x
  - tip

# Allow failure on Go tip, we just want to be able to track behavior there.
matrix:
  allow_failures:
    - go: tip

# Fetch vendored third-party dependencies and install a tool for merging
# coverage profiles.
before_install:
  - git submodule init
  - git submodule update
  - go get -u -v github.com/wadey/gocovmerge

# Skip the default install step since it doesn't make sense for Mutagen.
install: true

# Run tests, upload the coverage report (if not running on tip), and build
# bundles. We fold coverage report uploading into script to mirror the behavior
# on AppVeyor (which is necessary because AppVeyor's after_test doesn't seem to
# fail the build if an upload fails (which we want to do)).
# HACK: We have to use a custom script to invoke tests because we want a
# combined coverage report that includes all packages and go test currently
# doesn't support that. We should monitor golang/go#6909 and golang/go#21126 so
# that we can remove this workaround once that Go toolchain supports this
# natively.
script:
  - go version
  - go run scripts/ci_testing.go --race
  - if [[ "$TRAVIS_GO_VERSION" =~ ^1\.9(\.[0-9]+)?$ ]]; then bash <(curl -s https://codecov.io/bash) ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then go run scripts/build.go --mode=release ; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then go run scripts/build.go --mode=testing ; fi

# HACK: If we're doing a release deployment, convert the Windows bundles to zip
# format. This is a lot simpler than trying to add zip file support to the build
# script. Note that we don't convert the agent bundles - Mutagen knows how to
# read those and users don't need to unzip them (and shouldn't).
before_deploy:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then scripts/convert_windows_release_bundles.sh ; fi

# Upload build artifacts from macOS builders on tagged releases.
deploy:
  provider: releases
  api_key:
    secure: oGoH8k4iqfXizSDUNaFRMqG+q0hYjJcPQBkCSlDWC/enMtn2HyT4UI+vRCksastjNS6ltGrwlebKVyOzkWQCvN/apiteDHgcwPvaJr4ioEZ/UdNobbD2sRyQ6mntXZoQLmTCouDpj47xQA/8bpWSsKNJscIrWuzBr1IUCnDWGPR27ninXX7eueIB9W2BCiuaXvRcvOmLOQslQ+sZEsUjZ2tJ1IB2gQiQdE0yIeHR3A6WsEKkkQWecCnNvuuhtAJZ0bcvR/aKGm3NPPzmvNHu05whvb55qpWjVBdxExatHNXFal4xvesgmFGzlbxkTOHl6QMauuVPJ0ctAEsWMjeNGYHVtmjR7d9+bpgMhpTtxFz6j/HEVs1hzLcsE96LUkxsK6Mc6xpOVI41rsTMLNYIPqjcfBa4/VNUEBFbX8J68BhJ9Ou3zV1f1N1b4nm6PO3asfVgCbYQNTg0Yx3/27KlNzymccui/LmR3l9jbNdQ/KaH689ZFi6+kTL1U8/i/cPo3rv1goQM0vSbuUe9zoydlfCmn5mnFH85PV2/oW55NrTDoHOD6OMUMAma7c48I4+unVSdg4k3IM+YE0uXHJ/OyPifNUXgp+TMQRb5LerMfjvf7HMyMnPjZZsV4COb55hsdH3dx6Yp8BIUxtRV1yzWlBzRo3DIZ5QqYNydc4Cirok=
  skip_cleanup: true
  file:
    - build/mutagen_darwin_amd64.tar.gz
    - build/mutagen_dragonfly_amd64.tar.gz
    - build/mutagen_freebsd_386.tar.gz
    - build/mutagen_freebsd_amd64.tar.gz
    - build/mutagen_freebsd_arm.tar.gz
    - build/mutagen_linux_386.tar.gz
    - build/mutagen_linux_amd64.tar.gz
    - build/mutagen_linux_arm.tar.gz
    - build/mutagen_linux_arm64.tar.gz
    - build/mutagen_linux_mips.tar.gz
    - build/mutagen_linux_mips64.tar.gz
    - build/mutagen_linux_mips64le.tar.gz
    - build/mutagen_linux_mipsle.tar.gz
    - build/mutagen_linux_ppc64.tar.gz
    - build/mutagen_linux_ppc64le.tar.gz
    - build/mutagen_linux_s390x.tar.gz
    - build/mutagen_netbsd_386.tar.gz
    - build/mutagen_netbsd_amd64.tar.gz
    - build/mutagen_netbsd_arm.tar.gz
    - build/mutagen_openbsd_386.tar.gz
    - build/mutagen_openbsd_amd64.tar.gz
    - build/mutagen_openbsd_arm.tar.gz
    - build/mutagen_solaris_amd64.tar.gz
    - build/mutagen_windows_386.zip
    - build/mutagen_windows_amd64.zip
  on:
    repo: havoc-io/mutagen
    condition: '"$TRAVIS_OS_NAME" == "osx" && "$TRAVIS_GO_VERSION" =~ ^1\.9(\.[0-9]+)?$'
    tags: true

# Send notifications.
notifications:
  email:
    - jacob@havoc.io
