# Set the language.
language: go

# Set up the build matrix. The Travis macOS builders are really slow when
# performing integration tests (I suspect due to the underlying hardware), and
# they often go more than 10 minutes without any output while copying files
# (which Travis treats as failure), so we disable end-to-end integration tests
# on macOS builders. Even if Travis were to allow long periods without output,
# the macOS builders still have to do a full release build after testing, which
# takes a long time by itself, and it makes waiting for test and build results
# painful. We still get full integration test coverage on Linux and Windows, and
# all internals are tested on macOS, so this isn't a huge loss to coverage.
matrix:
  include:
    - os: osx
      osx_image: xcode9.4
      env:
        global:
          - GO111MODULE=on
          - MUTAGEN_TEST_SSH=true
    - os: linux
      env:
        global:
          - GO111MODULE=on
          - MUTAGEN_TEST_END_TO_END=true
          - MUTAGEN_TEST_SSH=true
          - MUTAGEN_TEST_DOCKER=true
          - MUTAGEN_TEST_DOCKER_BASE_IMAGE_NAME=alpine
          - MUTAGEN_TEST_DOCKER_IMAGE_NAME=mutagentest
          - MUTAGEN_TEST_DOCKER_CONTAINER_NAME=mutagentester

# Require use of sudo (we need this to set up SSH and use Docker).
sudo: required

# Require the use of Docker. This should have no effect on Travis' macOS
# infrastructure, where use of Docker is not supported.
services:
  - docker

# Set our Go version(s). Mutagen generally only supports a specific version of
# Go at a time, usually the latest.
# NOTE: When specifying versions with a trailing 0 (e.g. 1.10), you need to
# enclose the version in quotation marks for YAML to treat it as a string rather
# than a float to be truncated:
# https://github.com/travis-ci/travis-ci/issues/9247
go:
  - "1.11"

# Skip the default install step since it doesn't make sense for Mutagen.
install: true

# Perform setup for testing.
before_script:
  - source scripts/setup_ssh.sh
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then source scripts/setup_docker.sh ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then source scripts/create_test_partitions_darwin.sh ; fi

# Run tests, upload the coverage report, and build bundles. We have to run a
# quick build before running tests because the tests rely on the agent bundle
# being available. We don't want to do a full build to start with though because
# that can take a while. We fold coverage report uploading into the script
# section to mirror the behavior on AppVeyor (which is necessary because
# AppVeyor's after_test doesn't seem to fail the build if an upload fails (which
# we want to do)).
script:
  - go version
  - go run scripts/build.go --mode=slim
  - go test -v -race -coverpkg=./pkg/... -coverprofile=coverage.txt ./pkg/...
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then GOARCH=386 go run scripts/build.go --mode=slim ; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then GOARCH=386 go test -v ./pkg/... ; fi
  - bash <(curl -s https://codecov.io/bash)
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then go run scripts/build.go --mode=release ; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then go run scripts/build.go --mode=testing ; fi

# Perform teardown after testing.
# NOTE: This actually runs after before_deploy, but it's more logical to have it
# at this point in the file. See
# https://docs.travis-ci.com/user/customizing-the-build/ for more information.
after_script:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then source scripts/teardown_docker.sh ; fi

# HACK: If we're doing a release deployment, convert the Windows bundles to zip
# format. This is a lot simpler than trying to add zip file support to the build
# script. Note that we don't convert the agent bundles - Mutagen knows how to
# read those and users don't need to unzip them (and shouldn't).
before_deploy:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then scripts/convert_windows_release_bundles.sh ; fi

# Upload build artifacts from macOS builders on tagged releases.
deploy:
  provider: releases
  api_key:
    secure: oGoH8k4iqfXizSDUNaFRMqG+q0hYjJcPQBkCSlDWC/enMtn2HyT4UI+vRCksastjNS6ltGrwlebKVyOzkWQCvN/apiteDHgcwPvaJr4ioEZ/UdNobbD2sRyQ6mntXZoQLmTCouDpj47xQA/8bpWSsKNJscIrWuzBr1IUCnDWGPR27ninXX7eueIB9W2BCiuaXvRcvOmLOQslQ+sZEsUjZ2tJ1IB2gQiQdE0yIeHR3A6WsEKkkQWecCnNvuuhtAJZ0bcvR/aKGm3NPPzmvNHu05whvb55qpWjVBdxExatHNXFal4xvesgmFGzlbxkTOHl6QMauuVPJ0ctAEsWMjeNGYHVtmjR7d9+bpgMhpTtxFz6j/HEVs1hzLcsE96LUkxsK6Mc6xpOVI41rsTMLNYIPqjcfBa4/VNUEBFbX8J68BhJ9Ou3zV1f1N1b4nm6PO3asfVgCbYQNTg0Yx3/27KlNzymccui/LmR3l9jbNdQ/KaH689ZFi6+kTL1U8/i/cPo3rv1goQM0vSbuUe9zoydlfCmn5mnFH85PV2/oW55NrTDoHOD6OMUMAma7c48I4+unVSdg4k3IM+YE0uXHJ/OyPifNUXgp+TMQRb5LerMfjvf7HMyMnPjZZsV4COb55hsdH3dx6Yp8BIUxtRV1yzWlBzRo3DIZ5QqYNydc4Cirok=
  skip_cleanup: true
  file_glob: true
  file: build/release/mutagen_*_*v*
  on:
    repo: havoc-io/mutagen
    condition: '"$TRAVIS_OS_NAME" == "osx"'
    tags: true

# Send notifications.
notifications:
  email:
    - jacob@havoc.io
