# Set the build version.
version: "{build}"

# Set the clone folder so that Mutagen ends up in the GOPATH.
clone_folder: C:\gopath\src\github.com\havoc-io\mutagen

# Set Go versions.
environment:
  GOPATH: C:\gopath
  matrix:
    - GOROOT: C:\go
      RACEFLAG: -race
    - GOROOT: C:\go-x86
init:
  - set PATH=%GOROOT%\bin;%GOPATH%\bin;%PATH%

# Disable AppVeyor's default Visual Studio build system.
build: off

# Fetch vendored third-party dependencies.
before_test:
  - git submodule init
  - git submodule update

# Run tests.
# TODO: Figure out how to run the go test command with a pattern like "./..."
# without it descending into vendored packages, that way we don't need to
# manually specify packages.
test_script:
  - go version
  - go test -v %RACEFLAG% -cover github.com/havoc-io/mutagen/sync
  - go run scripts/build.go --mode=testing

# TODO: Once the go test command supports coverage profiles spanning multiple
# packages, use goveralls to upload a coverage report to coveralls.io. The
# relevant issue is here: https://github.com/golang/go/issues/6909.

# Send notifications.
notifications:
  - provider: Email
    to:
      - jacob@havoc.io
    on_build_success: false
    on_build_failure: true
    on_build_status_changed: true
