# Set the build version.
version: "{build}"

# Set the clone folder so that Mutagen ends up in the GOPATH.
clone_folder: C:\mutagen

# Set Go versions and environment variables.
# HACK: Disable the use of cgo. When using Go modules in Go 1.11, pre-compiled
# packages are not available (golang/go#26988), and Go will try to invoke gcc to
# compile those requiring C code. We could theoretically use the Mingw-w64
# toolchain available on AppVeyor, but that's a can of worms that I don't want
# to open. These packages are not essential to Mutagen's functioning, and they
# aren't used in Mutagen's release builds anyway. We can revisit enabling the
# pre-compiled C versions when Go 1.12 arrives, if it supports that with
# modules, but actually, since we use pure-Go alternatives in release builds,
# it's probably better to continue testing with those.
environment:
  GOROOT: C:\go111
  GO111MODULE: "on"
  CGO_ENABLED: "0"
  MUTAGEN_TEST_END_TO_END: "true"
init:
  - set PATH=%GOROOT%\bin;%PATH%

# Disable AppVeyor's default Visual Studio build system.
build: off

# Install the codecov.io Python-based upload tool.
before_test:
  - pip install codecov

# Run tests, upload the coverage report, and build bundles. We have to run a
# quick build before running tests because the tests rely on the agent bundle
# being available. We don't want to do a full build to start with though because
# that can take a while. We fold coverage report uploading into test_script
# because after_test doesn't seem to fail the build if an upload fails (which we
# want to do).
test_script:
  - go version
  - diskpart /s scripts/create_test_partitions_windows.txt
  - set MUTAGEN_TEST_FAT32_ROOT=V:\
  - go run scripts/build.go --mode=slim
  - go test -v -race -coverpkg=./pkg/... -coverprofile=coverage.txt ./pkg/...
  - set GOARCH=386
  - go run scripts/build.go --mode=slim
  - go test -v ./pkg/...
  - set GOARCH=amd64
  - codecov -X gcov -f coverage.txt
  - go run scripts/build.go --mode=testing

# Send notifications.
notifications:
  - provider: Email
    to:
      - jacob@havoc.io
    on_build_success: false
    on_build_failure: true
    on_build_status_changed: true
