# Set the build version.
version: "{build}"

# Set the clone folder so that Mutagen ends up in the GOPATH.
clone_folder: C:\gopath\src\github.com\havoc-io\mutagen

# Set Go versions.
environment:
  GOPATH: C:\gopath
  matrix:
    - GOROOT: C:\go
      RACEFLAG: -race
    - GOROOT: C:\go-x86
init:
  - set PATH=%GOROOT%\bin;%GOPATH%\bin;%PATH%

# Disable AppVeyor's default Visual Studio build system.
build: off

# Fetch vendored third-party dependencies.
before_test:
  - git submodule init
  - git submodule update

# Run tests.
# TODO: Go 1.9 will include a fix so that "..." patterns don't descend into
# vendor directories (https://go-review.googlesource.com/c/38745). Once 1.9 is
# out, we can consolidate these package-specific test commands into:
#   go test -v %RACEFLAG% -cover ./...
test_script:
  - go version
  - go test -v %RACEFLAG% -cover github.com/havoc-io/mutagen/multiplex
  - go test -v %RACEFLAG% -cover github.com/havoc-io/mutagen/sync
  - go test -v %RACEFLAG% -cover github.com/havoc-io/mutagen/url
  - go run scripts/build.go --mode=testing

# TODO: Once Go 1.9 lands, we'll be able to consolidate our tests and therefore
# generate a single cover profile. The current hacks to consolidate cover
# profiles are a pain (https://github.com/golang/go/issues/6909) and don't work
# very well. Once we have a single cover profile, start uploading it to
# coveralls.io.

# Send notifications.
notifications:
  - provider: Email
    to:
      - jacob@havoc.io
    on_build_success: false
    on_build_failure: true
    on_build_status_changed: true
