# Set the build version.
version: "{build}"

# Set the clone folder so that Mutagen ends up in the GOPATH.
clone_folder: C:\gopath\src\github.com\havoc-io\mutagen

# Set Go versions.
environment:
  GOPATH: C:\gopath
  matrix:
    - GOROOT: C:\go19
      RACEFLAG: -race
    - GOROOT: C:\go19-x86
init:
  - set PATH=%GOROOT%\bin;%GOPATH%\bin;%PATH%

# Disable AppVeyor's default Visual Studio build system.
build: off

# Fetch vendored third-party dependencies.
before_test:
  - git submodule init
  - git submodule update

# Run tests.
test_script:
  - go version
  - go test -v %RACEFLAG% -cover github.com/havoc-io/mutagen/message
  - go test -v %RACEFLAG% -cover github.com/havoc-io/mutagen/multiplex
  - go test -v %RACEFLAG% -cover github.com/havoc-io/mutagen/rsync
  - go test -v %RACEFLAG% -cover github.com/havoc-io/mutagen/sync
  - go test -v %RACEFLAG% -cover github.com/havoc-io/mutagen/url
  - go run scripts/build.go --mode=testing

# Send notifications.
notifications:
  - provider: Email
    to:
      - jacob@havoc.io
    on_build_success: false
    on_build_failure: true
    on_build_status_changed: true
