# Create the Docker Compose infrastructure when starting the project.
setup:
  - docker-compose up --build --detach

# Destroy the Docker Compose infrastructure when terminating the project.
teardown:
  - docker-compose down --rmi=all --volumes

# Define common utility commands.
commands:
  ipython: docker-compose exec jupyter ipython

# Forward local traffic to the Jupyter notebook server.
forward:
  jupyter:
    source: "tcp:localhost:8888"
    destination: "docker://data-science:tcp:localhost:8888"

# Synchronize analysis code and Jupyter notebooks with the container.
sync:
  defaults:
    ignore:
      vcs: true
  code:
    alpha: "analysis"
    beta: "docker://data-science/home/jovyan/data-science/analysis"
    mode: "one-way-safe"
  notebooks:
    alpha: "."
    beta: "docker://data-science/home/jovyan/data-science"
    mode: "two-way-safe"
    ignore:
      paths:
        - '*'
        - '!*.ipynb'
