# Create the Docker Compose infrastructure when starting the project.
setup:
  - docker-compose up --build --detach

# Destroy the Docker Compose infrastructure when terminating the project.
teardown:
  - docker-compose down --rmi=all --volumes

# Define common utility commands.
commands:
  database: docker-compose exec database psql -U messagessvc -d messagesdb
  logs: docker-compose logs --follow

# Forward local traffic to the web and API servers.
forward:
  api:
    source: "tcp:localhost:8081"
    destination: "docker://go-web-development:tcp:api:8081"
  web:
    source: "tcp:localhost:8080"
    destination: "docker://go-web-development:tcp:web:8080"

# Synchronize code to the shared Docker volume.
sync:
  defaults:
    ignore:
      vcs: true
  code:
    alpha: "."
    beta: "docker://go-web-development/development/code"
    mode: "two-way-resolved"
    ignore:
      paths:
        - "/*"
        - "!/api/"
        - "/api/*"
        - "!/api/{entrypoint.sh,go.mod,go.sum,server.go}"
        - "!/frontend/"
        - "/frontend/*"
        - "!/frontend/{entrypoint.sh,gulpfile.js,index.html,package*.json}"
        - "!/web/"
        - "/web/*"
        - "!/web/{entrypoint.sh,go.mod,go.sum,server.go}"
