# Set the Docker Compose file format.
version: "3.7"

# Define two containers: one to function as the development environment and one
# to serve as the tunnel host for synchronizing code and forwarding network
# traffic.
services:
  jupyter:
    build: ./containers/jupyter
    stop_grace_period: 0s
    volumes:
      - code:/home/jovyan/data-science
  tunnel:
    build: ./containers/tunnel
    environment:
      MUTAGEN_TUNNEL_UDP_PORT_MINIMUM: "62800"
      MUTAGEN_TUNNEL_UDP_PORT_MAXIMUM: "62900"
    ports:
      - "62800-62900:62800-62900/udp"
    volumes:
      - code:/home/jovyan/data-science

# Create a persistent shared volume to store and share synchronized code.
volumes:
  code:
