# Set the workflow name.
name: Release

# Execute the workflow whenever a tag is pushed. Release publication also
# generates a tag push event, so this covers both standard releases as well as
# one-off testing tags for which we might want release artifacts.
on:
  push:
    tags:
      - '*'

# Define the workflow job.
jobs:
  release:
    name: Release
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: '^1.15.6'
      - run: go version
      - run: scripts/ci/build.sh
      - uses: alexellis/upload-assets@0.2.3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          asset_paths: '["build/release/*"]'
